services:
  db:
    image: postgres:15
    container_name: echo_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: echodb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - echo_net

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: echo_backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5001:5001"

    # ✅ ADD THIS LINE TO IMPORT FROM .env
    env_file:
      - .env

    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: echodb
      DB_PORT: 5432
      # These will be overridden if defined in .env:
      GPT_API_KEY: ${GPT_API_KEY}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
      PORT: ${PORT}

    networks:
      - echo_net

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: echo_frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: "http://localhost:5001"
    volumes:
      - ./fe:/app
      - /app/node_modules
    networks:
      - echo_net

networks:
  echo_net:
    driver: bridge
