services:
  db:
    image: postgres:15
    container_name: echo_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: echodb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - echo_net

  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: echo_backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5001:5001"
    env_file:
      - constants.env   # Loads the environment from your .env file
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: echodb
      DB_PORT: 5432
      # If GitHub Actions sets OPENAI_API_KEY,
      # it can override the local .env by echoing "OPENAI_API_KEY=..." into .env
      # before docker-compose build
    networks:
      - echo_net

  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: echo_frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: "http://localhost:5001"
    volumes:
      - ./fe:/app
      - /app/node_modules
    networks:
      - echo_net

networks:
  echo_net:
    driver: bridge
