name: Deploy Echo Backend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GPT_API_KEY: ${{ secrets.GPT_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Confirm GPT_API_KEY is present
        run: |
          echo "🧪 GPT_API_KEY starts with: ${GPT_API_KEY:0:5}..."

      - name: Docker Compose Build and Up
        run: |
          echo "🛠 Running docker-compose up..."
          docker-compose -f docker-compose.yml up -d --build

      - name: Check backend logs
        run: |
          echo "📦 Checking backend logs..."
          docker logs echo_backend || true
